[build]
  base = "."
  publish = "public"
  command = "# no build step"

[[redirects]]
  from = "https://rainbow-citthora-be5202.netlify.app/ttt1"
  to = "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&daily=temperature_2m_max&timezone=auto"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://rainbow-citthora-be5202.netlify.app/ttt2"
  to = "http://www.amsskolkata.gov.in/data/kol_awos"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://rainbow-citthora-be5202.netlify.app/ttt3"
  to = "http://ciscobinary.openh264.org/openh264-2.3.1-2.fc38.x86_64.rpm"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "https://rainbow-citthora-be5202.netlify.app/ttt4"
  to = "https://wx.baf.mil.bd/METBSR/images/omar/RadarSingle/mtr.jpg"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
