[build]
  base = "."
  publish = "public"
  command = "# no build step"

[[redirects]]
  from = "https://rainbow-citthora-be5202.netlify.app/ttt1"
  to = "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m&daily=temperature_2m_max&timezone=auto"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
